# Generated by Django 5.2.7 on 2025-10-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classrom',
            field=models.CharField(max_length=200, verbose_name='Teacher Classroom'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Teacher Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='taddress',
            field=models.CharField(max_length=300, verbose_name='Teacher Address'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tname',
            field=models.CharField(max_length=200, verbose_name='Teacher Name'),
        ),
    ]
